### ISSUE TITLE
Redudant declaration in cached_layer.py

### ISSUE THREAD

**Issue by xiaolzha** [chafan-dev/chafan-core#1]
In chafan_core/app/cached_layer.py, the variable 'SUBMISSIONS_FOR_USER_CACHE_KEY' is declared twice at line 45 and 50.

It should be safe to delete one of them

**Comment by izgzhen** [comment]
Feel free to open a PR to delete :)

**Comment by xiaolzha** [comment]
Fixed this issue in PR #2
